---
title: "Initiating the International Training Modules of Open Scientific Practices"
author: "Sau-Chin Chen"
date: "2019/2/7"
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: fade
    incremental: true
---

# Latest Training Committee

## 

Associate Director: [Hans IJzerman](http://www.hansijzerman.org/)<br>
Assistant Directors: [Sau-Chin](http://scchen.com/), [Erin Buchanan](https://www.aggieerin.com/)<br>
Many enthusiastic Accelerators ...

# Guiding Principles of PSA training

## Who provide training?

- Any PSA member can share the approved training materials. 
    - If you want to submit your materials, just fill in [this form](https://docs.google.com/forms/d/1zkzqmedS_MWvGufwdoIUoOKvGRxf4-psCPJVFA35TH4/viewform?edit_requested=true).
- Training materials can be text or any type of multimedia.

## Training modules

- **PSA specific**: Overview of PSA network and projects. how to propose a PSA project; how to manage multi-lab data collection; how to organize PSA relative activities.

- **Methodological**: Research method/toolkits. how to use survey software; how to use research software.

- **Statistical**: Guides to conduct a specific analysis, statistical software, and a comprehensible report.

- **Open-Science**: Recommended practices for transparency, methodology, and general skills for open science. how to use GitHub, OSF; how to write reproducible document. 

## Distribution of approved training materials

- Three types of projects: (1) General purpose; (2)  PSA-specific; (3) PSA-requested.
- **We are going to assign four managers to each module.**
- **Translation issue**: Provided materials are not in (1) the committee's spoken languages and (2) committee's living area.
- **Distribution issue**: How to motivate scientists who are non-native English speakers to recognize/realize/appreciate Open Science practices?

## COS/PSA share the goals

>- [memo of COS/PSA](https://docs.google.com/document/d/1IBQ7r6Fku-qdf0NsBVEBB9agnXdduSZqjl5uGn7pk18/edit?usp=sharing)
>- deliver training & workshops (Training committee)
>- provide small grants to research teams as needed (Community committee)
>- engage additional disciplines

# Works to be initialized

## Missions

How to manage the systematic translations of training modules across languages/countries?<br>
<br>
How to foster the Open Science Communities in countries that are non-native English speakers?

## Team members

**Anchor members**: Stay in one mission till the end. Keep the [note](https://docs.google.com/document/d/1_RMbKn25HHMnZlvST897xZZXpiHNLQGdgdM3FrjXRkw/edit) of any suggestion. Give the hints for the swap members. One mission has 1 ~ 2 anchor member(s).

**Swap members**: Provide individual suggestions to the present mission. Switch to the other mission between Hacks. Rest of us are swap members.

## Schedule

|Stage|Activities|
|---|---|
|Brief|Introduction of this Hackthon|
|Select your mission|volunteer, lotty, ...|
|First Hack|Team discussions|
|Switch|Swap members jump to the other mission|
|Second Hack|Team discussions|
|Conclusion|Summary by anchor members|